phone_shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

phone_shop/db/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('', views.product_list, name='product_list'),

]

phone_shop/phone_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('db/', include('db.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phone_shop/db/models.py
from django.db import models
from django.urls import reverse



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])


class Product(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                    args=[self.id, self.slug])

phone_shop/db/views.py
from django.shortcuts import render, get_object_or_404

from cart.forms import CartAddProductForm
from .models import Category, Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'db/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'db/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

phone_shop/db/templates/db/detail.html
{% extends "db/layout_db.html" %}
{%load crispy_forms_tags %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-md-center">
            <div class="card mb-3" style="max-width: 1000px;">
                <div class="row g-0">
                    <div class="col md-4">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="img-fluid rounded-sart">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h1 class="card-title">
                                <p>{{ product.name }}</p>
                            </h1>
                            <p class="card-text">
                                <h2>Категория: <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
                            </p>
                            <p class="card-text">
                                <p class="price fs-3">Цена: ${{ product.price }}</p>
                            </p>
                            <p class="card-text fs-3">
                                Описание: <br><span class="fs-3">{{ product.description }}</span>
                            </p>
                            <p class="card-text">
                                <form action="{% url 'cart:cart_add' product.id  %}" method="POST">
                                    {{ cart_product_form|crispy }}
                                    {% csrf_token %}
                                    <input type="submit" value="Add to cart">
                                </form>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

phone_shop/db/templates/db/layout_db.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
  <div style="display: flex; flex-direction: column; height: 100vh;">
    <div id="header">
      <div class="container-fluid" style="background: url('/static/db/img/natural-paper.png'); padding-top: 25px;">
        <div class="row justify-content-md-center aliign-items-center">
          <div class="col-1">
            <a href="/db" class="logo"><i class="fa fa-home w3-xxxlarge"></i></a>  
          </div>
          <div class="col-3">
            <p class="h3">
              СмартфониЯ: Интернет магазин телефонов с доставкой по россии 
            </p>
          </div>
          <div class="col-3">
            <p class="h1">
              <span class="material-icons">
                call
              </span>
              8 800 333 22 33
            </p>
            <p class="h3">
              Рабтаем с 8:00 до 17:00 без выходных
            </p>
          </div>
          <hr>
        </div>
        <div class="row justify-content-md-center aliign-items-center fs-3">
          <div id="subheader" class="col-2">
            <div class="cart">
              {% with total_items=cart|length %}
                  {% if cart|length > 0 %}
                      Ваша корзина:
                      <a href="{% url "cart:cart_detail" %}">
                          {{ total_items }} товар{{ total_items|pluralize }},
                          ${{ cart.get_total_price }}
                      </a>
                  {% else %}
                      Your cart is empty.
                  {% endif %}
              {% endwith %}
          </div>
          </div>
        </div>
      </div>
    </div>
  
    <div id="content" style="flex-grow: 1;" class="bg-dark bg-opacity-25">
      {% block content %}
      {% endblock %}
    </div>
    <footer class="footer" id="footer">
      <div class="container-fluid p-4 bg-light" style="background: url('/static/db/img/natural-paper.png')">
        <div class="row justify-content-md-center align-items-center">
          <div class="col col-1 ">
            <i class="fa fa-home w3-xxxlarge"></i>
          </div>
          <div class="col-2">
            <p class="h5" style="padding-top: 10px;">
                Интернет магазин, 123456, г. Чебоксары, ул. Центральная 1, офис 1 <br>
                ИНН 1234567890 ОГРН 123456789012
            </p>
          </div>
          <div class="col-3">
              <div class="row">
                <p class="h1">
                    <span class="material-icons">
                      call 
                    </span>
                    8 800 333 22 33
                </p>
              </div>
              <div class="row">
                <p class="h3">
                  Звонок по России бесплатный
                </p>
          </div>
        </div>
      </div>
    </footer>
  </div>
</body>
</html>

phone_shop/db/templates/db/list.html
{% extends "db/layout_db.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <div class="container-fluid">
            <div class="row fs-3 justify-content-md-center" style="margin-top: 15px; min-width: 100%; background-color: #BF8F30; color: white;">
                <div class="col-1 text-center">
                    <p class="h3">
                        Категории
                    </p>
                </div>
            </div>
            <div class="row fs-3 justify-content-md-center" style="margin-top: 0px; min-width: 100%; background-color: #BF8F30; color: white; ">
                <div class="col-1 text-center">
                    <p {% if not category %} class="selected" {% endif %}>
                        <a href="{% url "shop:product_list" %}" class="text-decoration-none text-reset">All</a>
                    </p>
                </div>
                <div class="col-1 text-center">
                    
                    <div class="row">
                        {% for c in categories %}
                        <p {% if category.slug == c.slug %}class="selected"{% endif %}>
                            <a href="{{ c.get_absolute_url }}" class="text-decoration-none text-reset">{{ c.name }}</a>
                        </p>
                        {% endfor %}
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row justify-content-md-center">
            <div class="col-5">
                <p class="">
                    <h1>{% if category %}{{ category.name }}{% else %}Все товары{% endif %}</h1>
                </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-3 row-cols-md-1 g-4" style="justify-content: space-between">
            {% for product in products %}
            <div class="card fs-3 " style="width: 20rem; align-content: center; align-items: center ">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" style="max-width: 100px; max-height: 200px; margin: 10px;" class="car-img-top">                
                <div class="card-body">
                    <div class="card-title">
                        <p>
                            {{ product.name }}
                        </p>
                    </div>
                    <div class="card-text">
                        <p>
                            ${{ product.price }}
                        </p>
                    </div>
                    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Подробнее</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}