phone_shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

phone_shop/db/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('', views.product_list, name='product_list'),

]

phone_shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

phone_shop/phone_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('db/', include('db.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phone_shop/cart/models.py
from django.db import models

# Create your models here.

phone_shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, 
        coerce=int,
        label='Количество',
        
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

phone_shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from db.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

phone_shop/cart/templates/cart/detail.html
{% extends "db/layout_db.html" %}
{% load static %}
{% block title %}
Ваша корзина
{% endblock %}
{% block content %}
    
    <div class="container">
        <div class="row">
            <h1>Ваша корзина</h1>
        </div>
        <div class="row aliign-items-center ">
            <table class="table fs-3 text-center">
                <thead>
                    <th scope="col">Изображение</th>
                    <th scope="col">Назвние</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Удалить</th>
                    <th scope="col">Цена за шт.</th>
                    <th scope="col">Цена</th>
                </thead>
                <tbody>
                    <th scope="row"></th>
                    <td>
                        {% for item in cart %}
                        {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %}{% static "img/no_image.png" %}{% endif %}"  style="max-width: 100px; max-height: 200px; margin: 10px;" class="car-img-top">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>{{ item.quantity }}</td>
                            <td><a href="{% url "cart:cart_remove" product.id%}" class="btn btn-lg btn-primary">Удалить</a></td>
                            <td class="num">${{ item.price }}</td>
                            <td class="num">${{ item.total_price }}</td>
                        </tr>
                        {% endwith %}
                        {% endfor %}
                    </td>
                    <td>
                        <td>Total</td>
                        <td colspan="3"></td>
                        <td class="num">${{ cart.get_total_price }}</td>
                    </td>
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-3">
                <a href="{% url "shop:product_list" %}" class="btn btn-lg btn-primary">Продолжить покупки</a> 
                <a href="{% url "orders:order_create" %}" class="btn btn-lg btn-primary">Оформить заказ</a>  
            </div>
        </div>
    </div>
{% endblock %}